### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by starplanet** [New-Edge-Engineering/ansible-rundeck#29]
When I use `ansible-galaxy install neel.rundeck -p roles`, it will report the following error:

```
the full traceback was:

Traceback (most recent call last):
  File "/Users/zhangjinjie/.pyenv/versions/3.6.0/bin/ansible-galaxy", line 109, in <module>
    exit_code = cli.run()
  File "/Users/zhangjinjie/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ansible/cli/galaxy.py", line 138, in run
    self.execute()
  File "/Users/zhangjinjie/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ansible/cli/__init__.py", line 149, in execute
    fn()
  File "/Users/zhangjinjie/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ansible/cli/galaxy.py", line 386, in execute_install
    installed = role.install()
  File "/Users/zhangjinjie/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ansible/galaxy/role.py", line 242, in install
    loose_versions.sort()
  File "/Users/zhangjinjie/.pyenv/versions/3.6.0/lib/python3.6/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/Users/zhangjinjie/.pyenv/versions/3.6.0/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by mat-green** [comment]
This is most likely a problem with ansible galaxy rather than the role. If you can point me to a role you have successfully installed that I can check to see the differences.
